name: TLDR

on:
  schedule:
    - cron: '30 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4
      - name: Run script
        run: python scripts/scrap.py
      - name: |
          git config --local user.email anish.shobith19@gmail.com
          git config --local user.name Anish-Shobith
          git add .
          git commit -m "feat(add): ${{ steps.date.outputs.date }} tldr"
          git push
